spring:
  application:
    name: basic-example
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # or `validate`, `none`, `create`, `create-drop` depending on your need
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # or MySQL5Dialect if using older version

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: mysslkey
